//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cclearpro {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settingsinproggman : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settingsinproggman defaultInstance = ((Settingsinproggman)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settingsinproggman())));
        
        public static Settingsinproggman Default {
            get {
                return defaultInstance;
            }
        }
    }
}
